name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy site
    runs-on: ubuntu-latest
    container: docker.io/library/ruby:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy site
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
